version: "3.7"
services:
  jupyterlab:
    image: vonatzki/datascience-notebook:latest
    build: ./
    container_name: jupyterlab
    user: root
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - /home/vonatzki/Documents/jupyterlab-files:/home/jovyan/work
    ports:
      - "8890:8888"
      - "8050:8050"
      - "4040:4040"
    restart: "always"
