version: "3.7"
services:
  jupyterlab:
    image: vonatzki/datascience-notebook:latest
    build: ./
    container_name: jupyterlab
    user: root
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - ~/Documents/jupyterlab-files:/home/jovyan/work
      - /media/vonatzki/datasets:/home/jovyan/datasets
    ports:
      - "8890:8888"
      - "8050:8050"
      - "4040:4040"
    networks:
      - jupyterlab_docker
    restart: "always"
  # splash:
  #   image: scrapinghub/splash:latest
  #   container_name: splash
  #   ports:
  #     - "8050:8050"
networks:
  jupyterlab_docker:
    external: true
